#!/usr/bin/env bash
# Author: Abdalla Abdelmaksoud, M.S.
# CCBR, NCI
# (c) 2021
#
# wrapper script to run the snakemake pipeline
# a) on an interactive node (runlocal) OR
# b) submit to the slurm load scheduler (run)
#
# DISCLAIMER: This wrapper only works on BIOWULF

SNAKEMAKE_VERSION="snakemake/5.5.2"

sbatch runSM.bash --time=120:00:00

