## you probably need to change or comment/uncomment some of these

workpath: WORKDIR
fastqpath: FASTQPATH
index: "/data/khanlab/ref/telescopeERV/hg38UCSCbt2index/genome"
gtf: "/data/khanlab/ref/telescopeERV/hg38L1anndHERV.gtf"
